import assert from 'node:assert/strict';
import {mkdirSync,mkdtempSync,writeFileSync,readFileSync,readdirSync} from 'node:fs';
import {join} from 'node:path';
import {launchProbe,ROOT} from '../browser/probe-browser.mjs';
import {readLocalSecrets,readCloudflareSecrets} from '../../deployment/access/local-secrets.mjs';
import {dailyCode} from '../../deployment/access/core.mjs';
import {oracle,oracleInput} from '../browser/python-oracle.mjs';
import {compareResults} from '../browser/compare.mjs';
const origin=process.argv[2]??'http://127.0.0.1:4191';
const online=process.argv.includes('--online-cloudflare');
assert.ok(online?origin==='https://wind-curtailment-analysis.wind-curtailment-static-deployment.workers.dev':['http://127.0.0.1:4191','http://127.0.0.1:4192'].includes(origin),'explicit acceptance target only');
const tag=online?'cloudflare-production':new URL(origin).port,out=join(ROOT,'reports/browser-review/daily-access',tag);mkdirSync(out,{recursive:true});
const code=await dailyCode((online?readCloudflareSecrets():readLocalSecrets()).DAILY_ACCESS_SECRET),wrong=String((Number(code)+1)%1000000).padStart(6,'0');
const p=await launchProbe(null,'daily-access-'+tag,{remoteUrl:origin+'/?t0-harness&view=1&tab=dashboard',localWorkerPreview:!online,ready:'!!document.querySelector("#access-form")',readyTimeoutMs:online?60000:10000});
const checks=[],delay=ms=>new Promise(r=>setTimeout(r,ms));
async function wait(expr){for(let i=0;i<300;i++){if(await p.evaluate(expr))return;await delay(50);}throw Error('UI wait failed: '+expr+' '+JSON.stringify(await p.evaluate('({url:location.href,error:document.querySelector("#access-error")?.textContent,body:document.body.innerText.slice(-300)})')));}
async function set(selector,value){await p.evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(e.tagName==='SELECT'){e.value=${JSON.stringify(value)};}else Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,${JSON.stringify(value)});e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`);}
async function click(selector){await p.evaluate(`document.querySelector(${JSON.stringify(selector)}).scrollIntoView({block:'center'})`);const r=await p.evaluate(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);await p.call('Input.dispatchMouseEvent',{type:'mousePressed',...r,button:'left',buttons:1,clickCount:1},p.sessionId);await p.call('Input.dispatchMouseEvent',{type:'mouseReleased',...r,button:'left',clickCount:1},p.sessionId);}
try{
 assert.ok((await p.evaluate('location.pathname')).startsWith('/auth/login'));assert.equal(await p.evaluate('document.querySelector(".wind-upload")'),null);checks.push('unauthenticated app request lands on login');
 for(const width of [1280,903,665,390]){await p.call('Emulation.setDeviceMetricsOverride',{width,height:760,deviceScaleFactor:1,mobile:false},p.sessionId);assert.ok(await p.evaluate('document.documentElement.scrollWidth<=innerWidth+1'));const shot=await p.call('Page.captureScreenshot',{format:'png'},p.sessionId);writeFileSync(join(out,`login-${width}.png`),Buffer.from(shot.data,'base64'));}checks.push('responsive light layout at four sizes');
 await click('.theme');assert.equal(await p.evaluate('document.documentElement.dataset.scheme'),'dark');const dark=await p.call('Page.captureScreenshot',{format:'png'},p.sessionId);writeFileSync(join(out,'login-dark.png'),Buffer.from(dark.data,'base64'));await click('.theme');checks.push('native theme toggle');
 await set('#access-code','123');await click('.submit');assert.equal(await p.evaluate('document.querySelector("#access-code").validity.valid'),false);assert.equal(await p.evaluate('document.querySelector(".submit").disabled'),false);checks.push('invalid short code is blocked by form validation');
 await set('#access-code',wrong);await click('.reveal');assert.equal(await p.evaluate('document.querySelector("#access-code").type'),'text');await click('.reveal');assert.equal(await p.evaluate('document.querySelector("#access-code").type'),'password');checks.push('show hide code control');
 await click('.submit');await wait('document.querySelector("#access-error")?.textContent.includes("不正确")');assert.equal(await p.evaluate('document.querySelector("#access-code").value'),'');assert.equal(await p.evaluate('document.activeElement.id'),'access-code');checks.push('wrong code gives inline error without echoing the code');
 await set('#access-code',code);await click('.submit');await wait('!!window.__T0__ && !!document.querySelector(".wind-upload")');assert.ok(await p.evaluate('location.search.includes("view=1")'));checks.push('native form validates and securely loads actual dashboard');
 const cookies=(await p.call('Network.getCookies',{urls:[origin]},p.sessionId)).cookies.filter(c=>c.name==='__Host-wind-access');assert.equal(cookies.length,1);assert.equal(cookies[0].httpOnly,true);assert.equal(cookies[0].secure,true);checks.push('real browser accepts secure HttpOnly host cookie');
 const samples=join(ROOT,'docs/samples'),file=name=>{const b=readFileSync(join(samples,name));return {name,bytes:b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)};};
 const expected=await oracle({mode:'analyze',input:oracleInput({power:[file('minute-power.csv')],forecast:[file('forecast.csv')],options:{capacity:56,stationName:'本地口令验收场站',start:'2026-01-01',end:'2026-01-02'}})});
 await p.evaluate('document.querySelector("details.wind-upload").open=true');const {root}=await p.call('DOM.getDocument',{},p.sessionId);
 for(const [name,label] of [['minute-power.csv','分钟功率表文件'],['forecast.csv','数据下载预测表文件']]){const {nodeId}=await p.call('DOM.querySelector',{nodeId:root.nodeId,selector:`input[aria-label="${label}"]`},p.sessionId);await p.call('DOM.setFileInputFiles',{nodeId,files:[join(samples,name)]},p.sessionId);}
 await set('input[aria-label="场站名称"]','本地口令验收场站');await set('input[aria-label="装机容量"]','56');
 await p.evaluate(`document.querySelectorAll('.wind-upload input[type=date]').forEach((e,i)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,['2026-01-01','2026-01-02'][i]);e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));});document.querySelector('.wind-confirm input').click();`);
 await wait('!document.querySelector(".wind-upload button[type=submit]").disabled');await click('.wind-upload button[type=submit]');await wait('window.__T0__.state().stationName==="本地口令验收场站"');assert.deepEqual(await p.evaluate('window.__T0__.state().summary'),expected.summary);
 const downloads=mkdtempSync(join(out,'downloads-'));await p.call('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});await set('select[aria-label="导出内容"]','json');await click('.wind-export-controls button');
 let name;for(let i=0;i<200;i++){name=readdirSync(downloads).find(n=>n.endsWith('.json'));if(name)break;await delay(25);}assert.ok(name);assert.equal(compareResults(expected,JSON.parse(readFileSync(join(downloads,name),'utf8'))).equal,true);checks.push('after login real file upload Worker and full JSON export agree with Python');
 await p.call('Page.navigate',{url:origin+'/auth/logout?returnTo=%2F%3Fview%3D1%26tab%3Ddashboard'},p.sessionId);await wait('document.querySelector("#login-title")?.textContent.includes("退出")');await click('.submit');await wait('document.querySelector("#access-code")!==null');assert.equal((await p.call('Network.getCookies',{urls:[origin]},p.sessionId)).cookies.some(c=>c.name==='__Host-wind-access'),false);checks.push('native logout clears browser access');
 await p.call('Page.navigate',{url:origin+'/samples/forecast.csv'},p.sessionId);await wait('!!document.querySelector("#access-code")');assert.equal(await p.evaluate('location.pathname'),'/auth/login');checks.push('direct sample URL remains gated after logout');
 assert.deepEqual(p.browserErrors,[]);checks.push('no browser runtime errors');writeFileSync(join(out,'result.json'),JSON.stringify({passed:true,origin,checks},null,2));console.log(`Daily access browser ${tag}: ${checks.length} checks passed`);
}finally{await p.close();}
